export const mockData = {
  board: {
    _id: "board-id-01",
    title: "Team WD-51",
    description: "Pro MERN stack Course",
    type: "public", // 'private'
    ownerIds: [], // Những users là Admin của board
    memberIds: [], // Những users là member bình thường của board
    columnOrderIds: [
      "column-id-01",
      "column-id-02",
      "column-id-03",
      "column-id-04",
    ], // Thứ tự sắp xếp / vị trí của các Columns trong 1 boards
    columns: [
      {
        _id: "column-id-01",
        boardId: "board-id-01",
        title: " Board 01",
        cardOrderIds: [
          "card-id-01",
          "card-id-02",
          "card-id-03",
          "card-id-04",
          "card-id-05",
          "card-id-06",
          "card-id-07",
        ],
        cards: [
          {
            _id: "card-id-01",
            boardId: "board-id-01",
            columnId: "column-id-01",
            title: " Card 01",
            description: "Markdown Syntax (sẽ ở khóa nâng cao nhé)",
            cover:
              "https://www.elle.vn/wp-content/uploads/2020/03/08/393093/phim-hoat-hinh-vung-dat-linh-hon.jpg",
            memberIds: ["test-user-id-01"],
            comments: ["test comment 01", "test comment 02"],
            attachments: [
              "test attachment 01",
              "test attachment 02",
              "test attachment 03",
            ],
          },
          {
            _id: "card-id-02",
            boardId: "board-id-01",
            columnId: "column-id-01",
            title: "Card 02",
            description: "Markdown Syntax (sẽ ở khóa nâng cao nhé)",

            cover: null,
            memberIds: [],
            comments: [],
            attachments: [],
          },
          {
            _id: "card-id-03",
            boardId: "board-id-01",
            columnId: "column-id-01",
            title: "Card 03",
            description: null,
            cover: null,
            memberIds: [],
            comments: [],
            attachments: [],
          },
          {
            _id: "card-id-04",
            boardId: "board-id-01",
            columnId: "column-id-01",
            title: "Card 04",
            description: null,
            cover: null,
            memberIds: [],
            comments: [],
            attachments: [],
          },
          {
            _id: "card-id-05",
            boardId: "board-id-01",
            columnId: "column-id-01",
            title: "Card 05",
            description: null,
            cover: null,
            memberIds: [],
            comments: [],
            attachments: [],
          },
          {
            _id: "card-id-06",
            boardId: "board-id-01",
            columnId: "column-id-01",
            title: "Card 06",
            description: null,
            cover: null,
            memberIds: [],
            comments: [],
            attachments: [],
          },
          {
            _id: "card-id-07",
            boardId: "board-id-01",
            columnId: "column-id-01",
            title: "Card 07",
            description: null,
            cover: null,
            memberIds: [],
            comments: [],
            attachments: [],
          },
        ],
      },
    ],
  },
};
